name: yalingunayer.com CI Pipeline

on:
  push:
    branches:
      - master
      - dev
      - draft
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Image
        run: |
          REF_ID=${GITHUB_REF##*/}
          IMAGE_TAG="ygunayer/yalingunayer.com:$REF_ID"

          SHOULD_PUBLISH="0"
          re="refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+"
          if [[ "$GITHUB_EVENT_NAME" -eq "push" ]] && [[ "$GITHUB_REF" =~ $re ]]; then
              SHOULD_PUBLISH="1"
          fi

          docker build . --file Dockerfile --tag $IMAGE_TAG

          if [[ $SHOULD_PUBLISH -eq "1" ]]; then
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker push $IMAGE_TAG
          else
            echo "Commit ref $GITHUB_REF will not be published"
          fi
